---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Сайт мультиязычный (должен поддерживать 2 языка, Русский и Английский)
  - Пользователь при выборе нескольких категорий имеет возможность вернутся на главную страницу
  - Производительность сайта, интернет магазин должен выдерживать нагрузку в 1000 посетителей онлайн одновременно.
  - При добавлении товара в корзину можно выбрать количество
  - При оформлении заказа должно появляться окно с подтверждением заказа
